name: Scrape Kaufland Offers

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # KORREKTUR: Erst die Bibliotheken installieren...
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright beautifulsoup4 lxml

      # KORREKTUR: ...dann den install-Befehl von Playwright ausführen.
      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and push if changed
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add angebote.json
          git diff --staged --quiet || (git commit -m "Update angebote.json" && git push)
